SQL QUERIES TO QUESTIONS

---Question 1: Which apps have the highest rating in the given available dataset?

SELECT App, Category, Rating
FROM `myfirstsandboxp.reviews_data.app_data`
WHERE Rating = (SELECT MAX(Rating)
FROM `myfirstsandboxp.reviews_data.app_data`);


--Question 2: What are the number of installs and reviews for the above apps? Return the apps with the highest reviews to the top.

SELECT App, 
       Installs, 
       Reviews,
       Rating
FROM `myfirstsandboxp.reviews_data.app_data`
WHERE Rating = (SELECT MAX(Rating)
FROM `myfirstsandboxp.reviews_data.app_data`)
GROUP BY App, Installs, Reviews, Rating
ORDER BY Reviews DESC 
LIMIT 50;


-- Question 3: Which app has the highest number of reviews? Also, mention the number of reviews and category of the app

SELECT App, Category, Reviews
FROM `myfirstsandboxp.reviews_data.app_data`
ORDER BY Reviews DESC
LIMIT 1;

--Question 4: What is the total amount of revenue generated by the google play store by hosting apps? 
--(Whenever a user buys apps  from the google play store, the amount is considered in the revenue)

SELECT SUM(Price) as Revenue 
FROM `myfirstsandboxp.reviews_data.app_data`
WHERE Type = 'Paid';

--Question 5: Which Category of google play store apps has the highest number of installs? 
--also, find out the total number of installs for that particular category.

SELECT Category, 
                MAX(Installs) as Maximum_no_installs,
                        COUNT(Installs) as Total_no_of_installs
FROM `myfirstsandboxp.reviews_data.app_data`
GROUP BY Category
ORDER BY Total_no_of_installs DESC, 
         Maximum_no_installs DESC
LIMIT 5;


-- Question 6: Which Genre has the most number of published apps?

SELECT Genres,
       COUNT(Genres) AS Number_of_Apps
FROM `myfirstsandboxp.reviews_data.app_data`
GROUP BY Genres
ORDER BY Number_of_Apps DESC
LIMIT 2;


-- Question 7: Provide the list of all games ordered in such a way
--             that the game that has the highest number of installs
--             is displayed on the top (to avoid duplicate results use distinct)

SELECT DISTINCT
    App, MAX(Installs) AS maximum_no_of_installs
FROM
    `myfirstsandboxp.reviews_data.app_data`
WHERE
    Category = 'Game'
GROUP BY App
ORDER BY maximum_no_of_installs DESC;


--Question 8: Provide the list of apps that can work on android version 4.0.3 and UP.
SELECT App, 
       Android_Ver
FROM `myfirstsandboxp.reviews_data.app_data`
WHERE Android_Ver = '4.0.3 and up'
GROUP BY App, Android_Ver;


-- Question 9: How many apps from the given data set are free? Also, provide the number of paid apps

WITH p AS 
(SELECT *,
CASE WHEN type ="Free" THEN 1 ELSE 0 END AS freeapps,
CASE WHEN type ="Paid" THEN 1 ELSE 0 END AS paidapps
 FROM `myfirstsandboxp.reviews_data.app_data`
 )
 SELECT SUM(freeapps) AS total_free_apps, SUM(paidapps) AS total_paid_apps
 FROM p;


 -- Question 10: Which is the best dating app? (Best dating app is the one having the highest number of Reviews)

SELECT App, Reviews
FROM `myfirstsandboxp.reviews_data.app_data`
WHERE Category = 'Dating'
ORDER BY Reviews DESC
LIMIT 2;


--Question 11: Get the number of reviews having positive sentiment and number of reviews having 
--             negative sentiment for the app 10 best foods for you and compare them.

WITH d AS 
(SELECT *,
CASE WHEN Sentiment ="Positive" THEN 1 ELSE 0 END AS positive,
CASE WHEN Sentiment ="Negative" THEN 1 ELSE 0 END AS negative
 FROM `myfirstsandboxp.reviews_data.reviews`
 WHERE App = '10 Best Foods for You'
 )
 SELECT SUM(positive) AS total_positive, SUM(negative) AS total_negative
 FROM d;


 -- Question 12: Which comments of ASUS SuperNote have sentiment polarity and sentiment subjectivity both as 1?

SELECT Translated_Review, 
       Sentiment_Polarity,
       Sentiment_Subjectivity
FROM `myfirstsandboxp.reviews_data.reviews`
WHERE App = 'ASUS SuperNote' 
      AND Sentiment_Polarity = 1 
      AND Sentiment_Subjectivity = 1;


--Question 13: Get all the neutral sentiment reviews for the app Abs Training-Burn belly fat 

SELECT Translated_Review, 
       Sentiment
FROM `myfirstsandboxp.reviews_data.reviews`
WHERE APP = 'Abs Training-Burn belly fat' 
      AND Sentiment = 'Neutral';


--Question 14: Extract all negative sentiment reviews for Adobe Acrobat Reader with their sentiment polarity and sentiment subjectivity

SELECT Translated_Review, Sentiment_Polarity, Sentiment_Subjectivity
FROM `myfirstsandboxp.reviews_data.reviews`
WHERE App = 'Adobe Acrobat Reader' AND Sentiment = 'Negative';
